In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
meters = pd.read_csv('aaus3_class_meter_accounts - aaus3_class_meter_accounts.csv')
print(meters.shape)
print(meters.columns[:].tolist())
meters.info()

(360, 11)
['account_id', 'branch', 'customer_type', 'meter_type', 'read_date', 'previous_m3', 'current_m3', 'billed_m3', 'unit_rate_etb', 'invoice_etb', 'service_level']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   account_id     360 non-null    object
 1   branch         360 non-null    object
 2   customer_type  360 non-null    object
 3   meter_type     360 non-null    object
 4   read_date      360 non-null    object
 5   previous_m3    360 non-null    int64
 6   current_m3     360 non-null    int64
 7   billed_m3      360 non-null    int64
 8   unit_rate_etb  360 non-null    float64
 9   invoice_etb    360 non-null    float64
 10  service_level  360 non-null    object
dtypes: float64(2), int64(3), object(6)
memory usage: 31.1+ KB

In [7]:
meters.head()

,account_id,branch,customer_type,meter_type,read_date,previous_m3,current_m3,billed_m3,unit_rate_etb,invoice_etb,service_level
0,AC-41001,Bole,Residential,Mechanical,2026-01-01,900,907,1,8.0,8.0,Standard
1,AC-41002,Akaki,Commercial,Mechanical,2026-01-06,925,949,20,12.0,240.0,Priority
2,AC-41003,Kirkos,Institutional,Mechanical,2026-01-11,950,991,39,9.5,370.5,Standard
3,AC-41004,Lideta,Residential,Mechanical,2026-01-16,975,1033,58,8.0,464.0,Priority
4,AC-41005,Gullele,Commercial,Ultrasonic,2026-01-21,1000,1075,77,12.0,924.0,Standard

In [8]:
meters['usage_m3'] = (meters.current_m3- meters.previous_m3)
print(meters['usage_m3'].head().tolist())

[7, 24, 41, 58, 75]

In [9]:
meters.head()

,account_id,branch,customer_type,meter_type,read_date,previous_m3,current_m3,billed_m3,unit_rate_etb,invoice_etb,service_level,usage_m3
0,AC-41001,Bole,Residential,Mechanical,2026-01-01,900,907,1,8.0,8.0,Standard,7
1,AC-41002,Akaki,Commercial,Mechanical,2026-01-06,925,949,20,12.0,240.0,Priority,24
2,AC-41003,Kirkos,Institutional,Mechanical,2026-01-11,950,991,39,9.5,370.5,Standard,41
3,AC-41004,Lideta,Residential,Mechanical,2026-01-16,975,1033,58,8.0,464.0,Priority,58
4,AC-41005,Gullele,Commercial,Ultrasonic,2026-01-21,1000,1075,77,12.0,924.0,Standard,75

In [ ]:
view = meters.assign (usage_m3=lambda d:d.current_m3 - d.previous_m3,
gap_m3 =lambda d:d.current_m3 - d.previous_m3 - d.billed_m3
)
print(view['gap_m3'].head(3).tolist())

[6, 4, 2]

In [16]:
meters.head()
#meters.info()

,account_id,branch,customer_type,meter_type,read_date,previous_m3,current_m3,billed_m3,unit_rate_etb,invoice_etb,service_level,usage_m3
0,AC-41001,Bole,Residential,Mechanical,2026-01-01,900,907,1,8.0,8.0,Standard,7
1,AC-41002,Akaki,Commercial,Mechanical,2026-01-06,925,949,20,12.0,240.0,Priority,24
2,AC-41003,Kirkos,Institutional,Mechanical,2026-01-11,950,991,39,9.5,370.5,Standard,41
3,AC-41004,Lideta,Residential,Mechanical,2026-01-16,975,1033,58,8.0,464.0,Priority,58
4,AC-41005,Gullele,Commercial,Ultrasonic,2026-01-21,1000,1075,77,12.0,924.0,Standard,75

# Rename Columns

In [20]:
report = meters.rename(columns={'invoice_etb':'bill_etb','read_date':'reading_date'})
print('bill_etb' in report.columns)
print('reading_date' in report.columns)
meters.head()

True
True

,account_id,branch,customer_type,meter_type,read_date,previous_m3,current_m3,billed_m3,unit_rate_etb,invoice_etb,service_level,usage_m3
0,AC-41001,Bole,Residential,Mechanical,2026-01-01,900,907,1,8.0,8.0,Standard,7
1,AC-41002,Akaki,Commercial,Mechanical,2026-01-06,925,949,20,12.0,240.0,Priority,24
2,AC-41003,Kirkos,Institutional,Mechanical,2026-01-11,950,991,39,9.5,370.5,Standard,41
3,AC-41004,Lideta,Residential,Mechanical,2026-01-16,975,1033,58,8.0,464.0,Priority,58
4,AC-41005,Gullele,Commercial,Ultrasonic,2026-01-21,1000,1075,77,12.0,924.0,Standard,75

In [ ]:
s =  pd.Series([12,-5,27])
clean = s.where(s>=0,np.nan)
print(clean.to_list())

[12.0, nan, 27.0]

In [28]:
s = pd.Series([100,120,115,50,100])
print(s.diff().tolist())
print(s.pct_change().round(2).tolist())
running = s.cumsum()
print(running.tolist())
print(running.iloc[-1]==s.sum())

[nan, 20.0, -5.0, -65.0, 50.0]
[nan, 0.2, -0.04, -0.57, 1.0]
[100, 220, 335, 385, 485]
True

In [37]:
meters['read_date'] = pd.to_datetime(meters.read_date)

TypeError: <class 'function'> is not convertible to datetime, at position 0

In [31]:
meters.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   account_id     360 non-null    object
 1   branch         360 non-null    object
 2   customer_type  360 non-null    object
 3   meter_type     360 non-null    object
 4   read_date      360 non-null    object
 5   previous_m3    360 non-null    int64
 6   current_m3     360 non-null    int64
 7   billed_m3      360 non-null    int64
 8   unit_rate_etb  360 non-null    float64
 9   invoice_etb    360 non-null    float64
 10  service_level  360 non-null    object
 11  usage_m3       360 non-null    int64
dtypes: float64(2), int64(4), object(6)
memory usage: 33.9+ KB